### ISSUE TITLE
Cart item inputs wrap in <p> tags

### ISSUE THREAD

**Issue by WazzaJB** [ingenesis/shopp#3174]
Hi all,

When using `<?php shopp('cartitem','input'); ?>`, we can see `<p>` tags in the HTML. I believe this is due to:

````add_filter('shopp_cartitem_input_data', 'wpautop');```

at
```
https://github.com/ingenesis/shopp/blob/2fec36654bda5b740991144974212bcf9124b682/api/theme/cartitem.php#L16
```

Is this necessary? It unfortunately makes the options wrap onto new lines, which I do not believe is the intended result.

Would removing this have any unwanted side effects? Obviously the filter can be removed by the theme (as I am attempting), however I am documenting this here in case we can enhance it.

I found, using blame, that #2081 was the reason for this being added however I believe we need some sort of way of this only applying to textarea inputs.

Thanks :)

**Comment by msigley** [comment]
Some of this is a result of changes I helped make to the custom inputs. I don't see anything wrong with using wpautop here in my opinion. To remove the <p> tags you can remove the wpautop filter in you themes functions.php:
```php
remove_filter('shopp_cartitem_input_data', 'wpautop');
```
At the moment Shopp only has support for single line inputs.
To add the input name as part of the input data, I would filter on ```shopp_cartitem_input_data``` since the second argument to the filter is the input name:
```php 
add_filter('shopp_purchase_item_input_data', array($this, 'item_input_data'), 9, 2);
public function item_input_data($data, $name) {
	return $name.': '.nl2br($data);	
}
```

**Comment by msigley** [comment]
I think part of the issue here might also be the cartitem.inputs loop in cart.php in the default shopp theme. Here is the loop I use in my custom theme. I use product inputs extensively on all of our Shopp sites.
```php
<?php if(shopp('cartitem','hasinputs')): ?>
					    <ul>
					    <?php while(shopp('cartitem','inputs')): ?>
					    	<?php
					    	$input_name = shopp('cartitem','input','name&return=true');
					    	$input_name = preg_replace('/[_]+/', ' ', $input_name);
					    	?>
					        <li><strong><?php echo $input_name; ?></strong>: <?php shopp('cartitem','input'); ?></li>
					    <?php endwhile; ?>
					    </ul>
					<?php endif; ?>
```

**Comment by sierrab123** [comment]
This from https://shopplugin.net/support/topic/shopppurchasedata-outputs-the-data-wrapped-in-a-tag

"In order to fix this I had to go into purchase.php in the Shopp -> API -> theme folder...

add_filter('shopp_purchase_item_input_data', 'esc_html');
add_filter('shopp_purchase_item_input_data', 'wptexturize');
add_filter('shopp_purchase_item_input_data', 'convert_chars');
// add_filter('shopp_purchase_item_input_data', 'wpautop');

add_filter('shopp_purchase_order_data', 'esc_html');
add_filter('shopp_purchase_order_data', 'wptexturize');
add_filter('shopp_purchase_order_data', 'convert_chars');
// add_filter('shopp_purchase_order_data', 'wpautop');

**Comment by jonathandavis** [comment]
A better option is to add this to `functions.php`

```
remove_filter('shopp_purchase_order_data', 'wpautop');
```

**Comment by clifgriffin** [comment]
I agree with @jonathandavis and @msigley. Removing the filter and filtering to your own preference is sufficient here. Worst case scenario, someone could also override the block styling of the `<p>` tags, so developer knowledge is not required. (Not saying this is a GOOD solution, just saying it is not beyond the reach of less savvy devs. 

We can re-open if someone has a better idea, but this seems like the best way to render these by default. `nl2br` would be way more problematic.  You can't style `<br />` tags.
