### ISSUE TITLE
Card type details replaced with Credit Card in Payment Event Details

### ISSUE THREAD

**Issue by lorenzocaum** [ingenesis/shopp#3191]
Shopp 1.3.8, PayPal Pro, Authorizenet

When viewing an order in Shopp orders, you see the event details. Here is an example:

January 1, 2015 11:59 pm Payment authorized Credit Card (Visa 1234) | Transaction: 123123456789

In Shopp 1.3.8, the card-type or "Visa" in the example above will appear as Credit Card. Here is the updated example:

January 1, 2015 11:59 pm Payment authorized Credit Card (Credit Card 1234) | Transaction: 123123456789

**Comment by WazzaJB** [comment]
I believe "Credit Card" is the name you have given your payment options? If so, I am having an identical issue with SagePay.

I do not believe it is the Gateways fault, but that the issue lies:

https://github.com/ingenesis/shopp/blob/4ce73608150228535e45ba5d67ffd487d78d8699/core/flow/Checkout.php#L169

Removing this line has meant payments now go through fine.
