### ISSUE TITLE
Faulty API (1.3.8)

### ISSUE THREAD

**Issue by sierrab123** [ingenesis/shopp#3193]
Following a report at the HD, I tried the following API on my site <?php shopp('storefront.catalog-products','exclude = 1, 3, 7'); ?>

It makes no difference having the exclusion there, has this been deprecated? Or is the code incorrect on the API page?

(Yes I do accept the possibility that I am doing something wrong)

**Comment by sierrab123** [comment]
Update, no options are working

**Comment by jonathandavis** [comment]
remove the spacing… as in:

``` php
<?php shopp('storefront.catalog-products', 'exclude=1,3,7'); ?>
```

**Comment by sierrab123** [comment]
I am afraid that changed nothing

**Comment by sierrab123** [comment]
"It seems none of the values make it all the way through although they are present when the function starts"

**Comment by jonathandavis** [comment]
The exclude option here appears to exclude products in a given category ID, not individual products by product ID.

See https://shopplugin.net/api/storefront-catalog-products/ under the **exclude** option:

> **exclude**: No default value. Exclude specified (by id) categories from the category display.

**Comment by jonathandavis** [comment]
It's not really incorrect, but admittedly the description of the option could be improved.

**Comment by sierrab123** [comment]
That is what I am trying to do, it won't exclude the products in those categories

**Comment by ben72** [comment]
It did not seem when I tried the same. Product categories could not be excluded.

**Comment by jonathandavis** [comment]
I will do more research.

**Comment by Just-m** [comment]
Part of the problem is, the options set not being where they are expected to show up.
The code is checking `$options` to see whether the `exclude` option has been set.
That is not where the `exclude option` is present when set.

Changing `$options` to either `$this->_options` or `$this->loading` solves that problem.

The query won't work correctly when `term_taxonomy_id` and `term_id` are out of sync in term_taxonomy table.

current code:
`$this->loading['where'][] = "tr.term_taxonomy_id NOT IN ($exclude)";
$this->loading['where'][] = "tt.taxonomy = 'shopp_category'";`

could be changed to:
`$this->loading['where'][] = "tt.term_id NOT IN ($exclude) AND tt.taxonomy='shopp_category'";`

to solve that part.
Then, unfortunately it still doesn't work the way it did before. Some how pagination is off again, leaving empty spots (incomplete pages) for products filtered out.

All the above mentioned code starts here https://github.com/ingenesis/shopp/blob/0b0bebd9bf8fe263a7678ed7b942a6e21990969e/core/model/Collection.php#L1502

**Comment by ben72** [comment]
Incorrect pagination and empty spots, sounds just like the issue I've seen when using MixedCollection. I would really like to see this fixed.

**Comment by mccawphoto** [comment]
I am trying to exclude product categories as well and this is not working for me. I would love to see this fixed as well.

**Comment by msigley** [comment]
I have a workaround for this issue. You can use the following hasproducts call in your theme templates to exclude categories:
```
shopp('category',
		'hasproducts',
		array('load' => array('coverimages', 'categories'),
			'columns' => 'CAST(GROUP_CONCAT(tr.term_taxonomy_id) AS CHAR) AS term_taxonomy_set',
			'joins' => array("JOIN $wpdb->term_relationships AS tr ON (p.ID=tr.object_id)"),
			'having' => array("NOT FIND_IN_SET('category_id', term_taxonomy_set) AND NOT FIND_IN_SET('another_category_id', term_taxonomy_set)"),
			'groupby' => 'p.id'
			)
		)
```

**Comment by msigley** [comment]
Refined my workaround alittle bit. Its better to do this using the `shopp_{$slug}_collection_load_options` filter so we don't break shopp's pagination:
```
function shopp_catalog_collection_load_options( $loading ) {
		//Load Collection without Discontinued and Test Products
		//Test Products is term_taxonomy_id 112
		//Discontinued Products is term_taxonomy_id 108
		global $wpdb;
		$loading_overrides = array( 'columns' => 'CAST(GROUP_CONCAT(tr.term_taxonomy_id) AS CHAR) AS term_taxonomy_set',
			'joins' => array("JOIN $wpdb->term_relationships AS tr ON (p.ID=tr.object_id)"),
			'having' => array("NOT FIND_IN_SET('112', term_taxonomy_set) AND NOT FIND_IN_SET('108', term_taxonomy_set)"),
			'groupby' => 'p.id' );
		return array_merge($loading, $loading_overrides);
	}
	add_filter('shopp_catalog_collection_load_options', 'shopp_catalog_collection_load_options');
```
