### ISSUE TITLE
New order duplicate locking system causes loop

### ISSUE THREAD

**Issue by sierrab123** [ingenesis/shopp#3203]
Whilst checking out with PP, I believe that a loop sets in and returns you to the checkout page and that the new locking system is the guilty party

**Comment by lorenzocaum** [comment]
Was able to verify this issue on Shopp 1.3.8 and WP 4.1

**Comment by umarglobal** [comment]
Are you sure this issue has been fixed? I am getting redirected to the checkout page and cannot get past this using any and all payment gateways. Even with offline payment option. Using Shopp 1.3.8 and Wordpress 4.1

**Comment by crunnells** [comment]
I'm running into this same problem locally running MAMP. I had to comment out the whole locking section of the code because it wouldn't work with Test Mode or Offline Payment.

**Comment by umarglobal** [comment]
@crunnells not sure how to do that. As a consumer I just thought I would download the latest stable build thinking it would work. Can you please let me know which locking code section you commented out for the interest of everyone so that I can get my website working until this bug is fixed? Alternatively what is the solution for this major bug. Quite critical and need a resolution asap.

**Comment by crunnells** [comment]
@umarglobal if you click on the link for the issue (https://github.com/ingenesis/shopp/commit/62ab7c066acd07341904863d42311b3f93f63a3b) it'll show the changes that Jon made to fix the issue. 

If that doesn't work, just comment this whole section out: https://github.com/ingenesis/shopp/blob/62ab7c066acd07341904863d42311b3f93f63a3b/core/flow/Order.php#L261-278
