### ISSUE TITLE
Featured products cannot be sorted

### ISSUE THREAD

**Issue by dxdc** [ingenesis/shopp#3212]
The featured products category default to be sorted by newest, and does not respond to commands to have it sorted by title. The problem comes from this line of code in the core/model/Collection.php:

class FeaturedProducts extends SmartCollection {

        public static $slugs = array('featured');

        public static function name () {
                return Shopp::__('Featured Products');
        }

        public function smart ( array $options = array() ) {
                $this->loading['where'] = array("s.featured='on'");
                $this->loading['order'] = 'newest'; // this line is the culprit. 
        }

}

**Comment by jonathandavis** [comment]
The Featured Products smart collection is really a quick categorization feature of Shopp. Depending on your perspective on the Featured Products smart collection, adding a new product to the featured collection some might expect that product will show up first (as a newly featured product). This model works well when sites use the Featured Products collection for landing page slideshows, or other front-page products that are regularly rotated.

Obviously that's not the only way to use Featured Products so we just need to change the behavior from hard-coded to allowing optional overrides.

We're open to [Pull Requests](https://github.com/ingenesis/shopp/wiki/Submissions) if you want to submit one. Otherwise, it may take some time to get to. Our priorities are immediately focused on project Orion (1.4dev).
