### ISSUE TITLE
Free Shipping rate not appearing when a region or state/province is used

### ISSUE THREAD

**Issue by lorenzocaum** [ingenesis/shopp#3214]
Shopp 1.3.8

Create a free shipping option and set it to a region (e.g. South US) or a state/province (e.g. Florida).

Try to get a shipping rate. It won't appear.

Reset your session. Then go to the free shipping rate and adjust the requirements to USA. Then run the test again and it will show the free shipping option as expected.

**Comment by sierrab123** [comment]
Just following up on this as I have a ticket in on it.....

**Comment by jonathandavis** [comment]
I cannot get this to reproduce. I used both regions and state/province settings for the free shipping option. I tested the following:

- Free shipping, West US, checkout in California (option appears)
- Free shipping, West US, checkout in Ohio (no option)
- Free shipping, California, checkout in California (option appears) 
- Free shipping, California, checkout in Ohio (no option)
- Free shipping, South US, checkout in Florida (option appears)
- Free shipping, South US, checkout in Ohio (no option)
- Free shipping, Florida, checkout in Florida (option appears)
- Free shipping, Florida, checkout in Ohio (no option)

I must be missing something. Is the free shipping option the only option configured?

**Comment by crunnells** [comment]
I've checked this as well, and the Free Shipping option does show up in Checkout... Interesting to note though, that it doesn't show up in the cart. 

I have 3 options; Free Option when the state is Hawaii, a "Regular" Item Rate for US and CA, and an "Expedited" Item Rate for US and CA. When I enter a Hawaii zip code in the cart, it estimates the "Regular" item rate, rather than the preferred Free Rate (which, being more specific, I would think should have precedence). This is more of a preference thing than an actual issue, but I can't reproduce the reported issue.
