### ISSUE TITLE
Order status mapping UI not reflecting saved state

### ISSUE THREAD

**Issue by clifgriffin** [ingenesis/shopp#3242]
On Shopp 1.3.8 and WordPress 4.1.1 I'm seeing an issue where the order status mapping saves, but on page reload the UI doesn't reflect the saved state. 

Digging into it, it seems to be an issue with jQuery-tmpl and the JavaScript that sets the selected values.  

When this loop runs:
```js
$("#order-statuslabels select").each(function(i,menu){
		var menuid = $(menu).attr('id'),
			id = menuid.substr(menuid.indexOf('-')+1);

		if(states != null && states[id] != undefined)
			$(this).find("option[value="+states[id]+"]").attr("selected", "selected");
	});
```

It is only running twice, despite `$("#order-statuslabels select").length` being 4.  Very weird. 

My only guess is that the above code is running somehow before the jquery-tmpl has finished.  Though actually inspecting `$("#order-statuslabels select")` during the loop reveals the correct data. Which is really bizarre.

**Comment by jonathandavis** [comment]
I can't reproduce this issue @clifgriffin. I tried and tried, but ultimately failed. I'm not sure what is different in our environments.

What you're describing would indicate that only some of the elements of the template are added to the DOM before the loop runs. That's bizarre, because if any of them get added at all, they should all add, none of this partial stuff.

Question: what changes were you making to the order status labels (adding 2 labels at a time, or removing multiple at a time, or just adding one, or change status mapping)?

**Comment by clifgriffin** [comment]
@jonathandavis The issue is that the UI loads with none of the values from the database. 

So it isn't really based on a particular scenario.  

Also of note, the first value always fills in because that row is there by default.

**Comment by jonathandavis** [comment]
Any new information I can use to try to reproduce this issue? If not I'm going to bump this issue to Orion.

**Comment by clifgriffin** [comment]
@jonathandavis More information: only happens on one of my subsites.  So it's possible it's a niche multisite issue. 

I just sent you an invite to create a user on the staging subsite involved.  I'll send you FTP creds via Slack.

**Comment by jonathandavis** [comment]
Thanks @clifgriffin for the env access so I could see this issue. It was throwing the following error:

> Error: Syntax error, unrecognized expression: option[value=]
