### ISSUE TITLE
All products inserted with author id 0, no way to separate shopp_users with edit_others_posts

### ISSUE THREAD

**Issue by isvaljek** [ingenesis/shopp#3320]
When a shopp_product is added in admin it's added in wp_posts with author id = 0, we're trying to separate visible/editable products on a per user scenario. Is there another way to accomplish this since edit_others_posts capability won't work for user = 0.

**Comment by sierrab123** [comment]
Hi , try requesting help on this in the Community Forum, Help Desk or the WP support thread as this is only for issues in the core,

**Comment by msigley** [comment]
@isvaljek: Did you try adding products as a different user than the admin account?

**Comment by isvaljek** [comment]
@msigley Yes we tried adding products as different users, also different roles.
You can try on vanilla wp/shopp install, see for yourself in wp_posts.

**Comment by Just-m** [comment]
If you, just for testing, change the author_id  for some posts in the wp_posts table to different authors. Does it react the way you want it to work?

**Comment by isvaljek** [comment]
I think not, but it could also be that i'm not using 'edit_others_posts' the right way.

**Comment by Just-m** [comment]
You think not or you tried it and it didn't work?

**Comment by isvaljek** [comment]
I could not get it to work as i wanted it. Don't know if it's because of some core bug or i didn't add the filter correctly:
I have found this in the core, and tried to add_filter in the functions.php
apply_filters( 'shopp_product_capabilities', array(
			'edit_post' => 'shopp_products',
			'delete_post' => 'shopp_products'
		) );

**Comment by crunnells** [comment]
I think the solution is going to be more involved than just setting the author ID. I could be wrong here, but looking at it there isn't really any granularity for product permissions in Shopp; either you have permission to edit all of them or you don't have permission to edit any of them. My understanding of WP roles and capabilities isn't the best, but I think you'll need to check permissions manually. Refer to this tutorial: http://justintadlock.com/archives/2010/07/10/meta-capabilities-for-custom-post-types

You'll find the filter code near the bottom of the post, and you'll need to change it to work with Shopp's roles ('shopp_product' mainly). Of course, you'll also need to setup an action to set the author ID during 'shopp_save_product' (set `$this->post_author = get_current_user_id();` before the product is saved) so that you can make sure some roles can only edit products they've authored.

**Comment by Just-m** [comment]
@Chris my thoughts exactly, that is why I suggested to test it with adjusted author_ids. The article you refer to is a good read.

**Comment by isvaljek** [comment]
how do i utilize the shopp_save_product, it's not mentioned in the api?

**Comment by crunnells** [comment]
It's just an action hook (see the [action reference](https://codex.wordpress.org/Plugin_API/Action_Reference) page for an explanation), and it runs just before the product is saved. You could also use the ['save_post'](https://codex.wordpress.org/Plugin_API/Action_Reference/save_post) action hook, but 'shopp_save_product' is more specific.

**Comment by isvaljek** [comment]
@crunnells Thanks for the article, but in there is a chunk of add_action( 'init', 'create_my_post_types' ); and that seems to be the place to enum post capabilities
'capabilities' => array(
				'publish_posts' => 'publish_movies',
				'edit_posts' => 'edit_movies', ...
I don't know if i can have any control over it, since the shopp_product post registration is inside core files.

**Comment by crunnells** [comment]
You don't need to re-register or change the post type capabilities, you just need to define the capabilities based on what you're trying to do. If you're setting the author ids for products (using the 'shopp_save_product' action hook), you just need to change the `my_map_meta_cap` function in the example to limit access to 'shopp_products' if the user is trying to access a product that isn't theirs, while making sure admins can access all products.

**Comment by msigley** [comment]
Please move the support discussion here to the WordPress.org support forums or the shopplugin.net helpdesk.

If there is no further discussion on implementing post authors on shopp products I'll be closing this issue.

It seems the intention of this issue is a feature request for author permission roles on shopp products. Please open up a separate issue for that please.

-----Original Message-----
