### ISSUE TITLE
When Stores with VAT enabled sell outside the VAT territory, sub totals can be shown as incorrect

### ISSUE THREAD

**Issue by sierrab123** [ingenesis/shopp#3364]
Easy to recreate
Make the taxes inclusive
Set a rate
Purchase a product from outside the VAT area
Increase the amount purchased of that product and a discrepancy will occur in the sub total in some cases

**Comment by crunnells** [comment]
Do you have other information, specifically what kind of math you're seeing? That will help troubleshoot this issue.

**Comment by sierrab123** [comment]
If you have a test rig it's very easy to recreate. Let's say you have a VAT rate of 10% and the products are listed in in the product editor with tax included. If you sell a product outside that tax area (eg merchant in France sells to USA) then shopp will divide the gross price by 1.10 to display the net price to the purchaser in the cart once you put have put in the country in "Estimate Taxes and shipping" dialog boxes. If you then increase the number of products you will see a discrepancy appear in the line total. I have seen it in all of the cases I have tried.

The issue is compounded by what appears PayPal calculating in a slightly different way (different rounding maybe) and returning what appears to be a different amount showing a balance of plus or minus 1 cent when there is only one line of products in the cart.

I realize that VAT may cause a nightmare for those based in Hawaii who do not have to deal with it @crunnells !! 

I have seen a 3 cent difference when there are 3 lines of products in the carts.

Although I have not enough research it may be down to the fact that in some situations the maths returns a result with a recurring result and it may be this that causes the issue

**Comment by brookebillett** [comment]
This what PayPal  had to say:

Hi Brooke,
Thank you for contacting PayPal Merchant Technical Support. My name is Sheela and I will be assisting you with your inquiry.

As I understand it, the transaction amount does not tally with the invoice issued by SHOPP.

Brooke, based on my investigation on transaction log, I noticed that the amount passed to Paypal is $346.64 as per shown in the log shared below and the same amount is being authorized.
 
Timestamp
Aug 5, 2015 13:33:14 (1438752794)
EventName
FlowWPSOneXCartPaymentStart
flowlogging_id
3f38bf40b3ff5
CAL
6f933861fa84
feed
ULA
EventTime
1438752794547
buyer_ip
111.240.193.196
flow_type
WPS
switch_value
tnc-a-wps-cntl
fga_status
not_enabled
fga_experience
FGA_DEFAULT
counter_party
1384243952716773827
invoice_id
67
custom
f661b2348b70fdf7455b697fd2a6f63f
referral_url
https://www.hopesrelief.com.au/shop/checkout/
ReturnURL
http://www.hopesrelief.com.au/shop/checkout/?rmtpay=4a029bbd&utm_nooverride=1
button_source
shopplugin.net[WPS]
notify_url
https://www.hopesrelief.com.au/shop/checkout/?_txnupdate=4a029bbd
charset
utf-8
pymt_action
2
cancel_url
https://www.hopesrelief.com.au/shop/cart/
is_cookied_user
1
locale
TW
time_last_redirected
1438752794
amt
34664
 
In order to solve this issue, I would suggest you to contact SHOPP technical support to assist you further on this issue since the invoice was generated from their end. Kindly seek their assistance to check on the mismatch on the transaction amount with the invoice issued.

I hope I was able to address your inquiry to your satisfaction, should you have further questions relating to this inquiry or any other issue, please do not hesitate to let me know.

Thank you.
 
Sincerely,
Sheela
Merchant Technical Support
PayPal

**Comment by sierrab123** [comment]
Looks like this was listed before https://github.com/ingenesis/shopp/issues/1889.  It is driven more by the amount ordered. I can recreate the error at will on a test site, once I introduce quantities into the mix. With only one ordered of a product, there is no issue, it's when there are multiples. What I can't be sure of is if this is a rounding error or a transactional error or another sort of error such as a display error. I just don't know.

**Comment by sierrab123** [comment]
It appears that there is something called a float truncation error that might be causing this.

**Comment by brookebillett** [comment]
Hello! Just wondering if there had been any progress with this job. The business owner is looking at changing from SHOPP to Woo-commerce if the issue isn't resolved soon, Would be a shame as lots of work has gone into customising and setting up his online store. Any indication of timeline I could pass on to him?

**Comment by sierrab123** [comment]
This problem has to occur in a non rounding of the net number after the VAT has been removed by division. I have looked through all the various files that seem to relate to inclusive taxes and cannot find a rounding function there.

**Comment by brookebillett** [comment]
Dear SHOPP team,

I did some digging around on Wordpress forums, and it seems that WooCommerce has a similar problem. Can you please review this content, and advise if this strategy could be applied to SHOPP? 

WooCommerce - excelling eCommerce
Paypal Standard Rounding Error - documented in earlier versions (1 post)
		 
		sliquid
		Member Posted 10 months ago #   But I have a different version than other posts, so creating my own. WordPress version 3.9.2 WooCommerce Version 2.1.12 The problem is with the rounding. The amount passed to Paypal including tax and shipping is not the amount the cart shows (usually off by .01), and thus give the error: Validation error: PayPal amounts do not match woo commerce And the order status goes to on-hold. Others have posted this same problem for several previous versions. https://wordpress.org/plugins/woocommerce/

		darkskycreations
		Member Posted 1 year ago #   Im receiving a Validation Error from Paypal: Validation error: Paypal amounts do not match. Order status changed to hold. I did some investigation and found that whatever price is being displayed on the woocommerce checkout page is correct eg $6.54. But when it is being pass onto paypal side that is not the case eg. ($6.54 is rounded to $6.50) Has anyone encounter such problems? Im just trying to rule out its not this plugin thats causing the bug.  Any solutions is much appreciated. thanks http://wordpress.org/plugins/woocommerce-bulk-discount/   
		 
		cjurczak
		Member Posted 1 year ago #   I am getting an error from Paypal:
		10413: The totals of the cart item amounts do not match order amounts. I suspect a rounding problem as well. It only happens on certain % discounts.  I was going to take a site live this week, but cannot without this functionality working.   
		 
		cjurczak
		Member Posted 1 year ago #   It seems to be any discounted % over 60.004% with a quantity of 1000 that gives me the trouble.  And 60.02 with a quantity of 100, gives me the same problem.   
		 
		Djinn22
		Member Posted 9 months ago #   did you guys figure this out??   
		 
		Craig Cooper
		Member Posted 9 months ago #   I'm getting this very same error. I think if we could round the amount at the point of discount it will solve the problem. In my case I have 0.85 with a 15% discount which is 0.7225. Unfortunately paypal receives 0.72 and so with any quantity greater than 4 there is a mismatch in paypal's calculation of the amount and WooCommerce's.   
		 
		Craig Cooper
		Member Posted 9 months ago #   I'd be happy to modify the code myself if I knew where to add the code to round the figure .   
		 
		Craig Cooper
		Member Posted 9 months ago #   Ok, so I dug into the code and I found this at line 366: $row_base_price = $_product->get_price() * $this->discount_coeffs[$this->get_actual_id( $_product )]['coeff']; I changed it to this: $row_base_price = round($_product->get_price() * $this->discount_coeffs[$this->get_actual_id( $_product )]['coeff'],2); And now the prices are rounded BEFORE they are calculated. So if your price is 0.7525 or something similar after the discount is calculated it is rounded to two decimal places (standard for many currencies) before it is multiplied by the quantity for the subtotal. So the discount is technically less precise but it means you can actually checkout with Paypal.

**Comment by sierrab123** [comment]
Getting a bit closer to the real issue here. Looked at this with @Just-m over the last couple of days
The problem is actually caused by the fact that PayPal redoes the sums and comes up with a different answer to shopp.

Both are "correct" based on the actual information that they work on

After calculating the net cost and presenting it as 2 digital place number in the cart, Shopp then performs a multiplication when there are more than one of the product, on the underlying number which is a 4 decimal place number

PayPal on the other hand performs the multiplication on the 2 decimal place number and gets a different result

I am not sure if there any other gateways that perform the same multiplication if there are then there may need to be a bit of a rethink. if it is only PP Std which does this then we could fix that file only.

**Comment by crunnells** [comment]
The (relatively) easy solution would be to just force Shopp to round the price after each operation, rather than rounding when we display the prices to the front end. This should satisfy the problem with PayPal, at the expense of under-charging by 0.01 every once in a while.

**Comment by Just-m** [comment]
Using an example product of Euro 15,00 and inclusive tax rate of 10%

The net price of the product would be Euro 13,63636363 which rounds to Euro 13,64
When ordering 10 pieces of this product you expect the line total to be 136,40  (being 10 * rounded net price)

Instead the cart overview shows  a line total of Euro 136,36
This may seem wrong but if you take 10 * Euro 15,00 = Euro 150,00 and calculate net price from that, you'll end up with Euro 136,36

One way is to change the way Shopp calculates things.
Another way is to change what is being sent to PP.
Instead of sending all products with their prices and quantities, send the whole order as one product with subtotal as product price. In that case PP will not recalculate the subtotal by multiplying quantitiy and price.

**Comment by sierrab123** [comment]
Reading back through this thread and looking at that reply from PayPal, it seems a bit disingenuous of them to suggest that they only deal with what they are sent.

If you look at this
http://www.awesomescreenshot.com/04557dc0ef
and then at what PayPal does with the info
http://www.awesomescreenshot.com/08d57dc318

You can see a 4c difference

On the original HD question I noticed that it can be a positive or negative difference

**Comment by Just-m** [comment]
Following up on my earlier suggestion to adjust what is being sent to PP.

Find this piece of code (it is at line 507 of Master)

```php
	foreach ( $Order->Cart as $i => $Item ) {
				$id++;
				$_[ 'item_number_' . $id ]		= $id;
				$_[ 'item_name_' . $id ]		= $Item->name . ( ! empty($Item->option->label) ? ' ' . $Item->option->label : '');
				$_[ 'amount_' . $id ]			= $this->amount($Item->unitprice);
				$_[ 'quantity_' . $id ]			= $Item->quantity;
				// $_['weight_'.$id]			= $Item->quantity;
			}
```

replace it with

```php
	foreach ( $Order->Cart as $i => $Item ) {
				$id++;
				$_[ 'item_number_' . $id ]		= $id;
				$_[ 'item_name_' . $id ]		= 'Set of ' . $Item->quantity . ' ' . $Item->name . ( ! empty($Item->option->label) ? ' ' . $Item->option->label : '');
				$_[ 'amount_' . $id ]			= $this->amount($Item->unitprice * $Item->quantity);
				$_[ 'quantity_' . $id ]			= 1;
				// $_['weight_'.$id]			= $Item->quantity;
			}

```
Be aware of the } at the last row

Instead of sending:
quantity = 10, name = product x, price = product unit price
we are sending:
quantity = 1, name = set of quantity product x, price = quantity * product unit price

This doesn't solve the cart display of unit price 13,64 and 136,36 when buying 10 pieces, but it should solve the payment difference issue.

**Comment by Just-m** [comment]
Minor update so the adjustment is only performed  when quantity is larger than 1.

```php
    foreach ( $Order->Cart as $i => $Item ) {
                $id++;
                $_[ 'item_number_' . $id ]      = $id;

                if ( $item->quantity > 1 ) {
                      $_[ 'item_name_' . $id ]        = Shopp::__('Set of') . ' ' . $Item->quantity . ' ' . $Item->name . ( ! empty($Item->option->label) ? ' ' . $Item->option->label : '');
                      $_[ 'amount_' . $id ]           = $this->amount($Item->unitprice * $Item->quantity);
                } else {
                      $_[ 'item_name_' . $id ]        = $Item->name . ( ! empty($Item->option->label) ? ' ' . $Item->option->label : '');
                      $_[ 'amount_' . $id ]           = $this->amount($Item->unitprice);
                }

                $_[ 'quantity_' . $id ]         = 1;
                // $_['weight_'.$id]            = $Item->quantity;
            }
 ```

**Comment by Just-m** [comment]
I realized this only needs to trigger when there is a difference between (quantity * round(unit_price)) and round(line-item total). 

```php
    foreach ( $Order->Cart as $i => $Item ) {
                $id++;
                $_[ 'item_number_' . $id ]      = $id;
                $_[ 'item_name_' . $id ]        = $Item->name . ( ! empty($Item->option->label) ? ' ' . $Item->option->label : '');
                $_[ 'amount_' . $id ]           = $this->amount($Item->unitprice);
                $_[ 'quantity_' . $id ]         = $Item->quantity;
                // $_['weight_'.$id]            = $Item->quantity;

                if ( $item->quantity > 1 ) {
                      $pp_price = round($Item->unitprice) * $Item->quantity;
                      if ( ! $pp_price == round($Item->totald) ) {
                          $_[ 'item_name_' . $id ]        = Shopp::__('Set of') . ' ' . $Item->quantity . ' ' . $Item->name . ( ! empty($Item->option->label) ? ' ' . $Item->option->label : '');
                          $_[ 'amount_' . $id ]           = $this->amount($Item->unitprice * $Item->quantity);
                          $_[ 'quantity_' . $id ]         = 1;
                      }
                }

            }
```

**Comment by sierrab123** [comment]
@Just-m just tested latest version, it works fine, you should make a PR for it

**Comment by brookebillett** [comment]
Hello! I am not code-conversant. But implemented what was suggested a few
days ago and did a test multiple order on PayPal. Amounts matched.

Do I need to do something new now?



Warm regards,

*Brooke Billett*


*0401 259 115*


<http://www.powersavvy.com.au/>

**Comment by sierrab123** [comment]
@jonathandavis could you review that PR https://github.com/ingenesis/shopp/pull/3374 from @Just-m and then I can close this

**Comment by Just-m** [comment]
PR-ed in #3374
