### ISSUE TITLE
shopp_captured_order_event and PayPal

### ISSUE THREAD

**Issue by teufelmartin** [ingenesis/shopp#3605]
I try to add a pdf to the captured email, but if my customer pays per paypal this event didn't get fired. It works for offline payments perfect.

```
add_action( 'shopp_captured_order_event', array( $this, 'attach_invoice_to_email' ));
```

Has anyone else experienced this issue?

**Comment by crunnells** [comment]
That's probably the wrong action to use. I'm not sure that PayPal Standard ever fires the Captured order event, which is more for credit card transactions where the payment is authorized at the time of sale, then captured at the time of shipment.

I'd suggest using the `shopp_order_success` instead, which should fire on any payment gateway when the order is complete.

**Comment by teufelmartin** [comment]
Thank you, this hook works for creating my invoice. But i didn't found a way of adding my PDF to the email-captured.
So I ended up of changing the email method of Core.php. But to my surprise Paypal do not use this method, because var_dump + exit didn't show as output. 
Is this possible?

**Comment by teufelmartin** [comment]
@crunnells, i spoke to Steve and i use Paypal Express of Shopp Core and right now i setup paypal pro for paypal express. But both results in the same problem.

**Comment by crunnells** [comment]
I looked into it, and `shopp_order_success` is supposed to fire right before the customer is redirected to the Thank You page (on a successful order+payment). Even if your customer pays with PayPal and doesn't ever return to the site, the action should still run if the PDT or IPN response returns successfully. Turn on debugging and make sure you see an IPN response in your logs, in which case `shopp_order_success` should be firing.

Since you're sending emails anyway, you could hook to the `shopp_order_notifications` instead, which sends out the order receipt. It runs alongside `shopp_order_success` in a lot of instances, but if your customers are receiving their order emails, then you'll know the action is running. It should help narrow down the issue with your hooked function.

**Comment by teufelmartin** [comment]
Hi Chris,
thank you for your explantation.
