### ISSUE TITLE
Merge Adjust taxsystem to properly calculate taxamount for inclusive/exclusive prices.

### ISSUE THREAD

**Issue by jonathandavis** [ingenesis/shopp#3723]
Merge changes from:

- https://github.com/ingenesis/shopp/commit/3e3bf02ff4c50a8d932abbd7c85ea43d1bd9bcf6
- https://github.com/ingenesis/shopp/commit/4665e0f5c3cc4978517f127e6b54584bf6a50605
- https://github.com/ingenesis/shopp/commit/00de1f2e34f716ff265f2f828ecd18e5c709d095
- https://github.com/ingenesis/shopp/commit/65b9fa211f16b0de6d58768379bc6ea9e33fe0f8
- https://github.com/ingenesis/shopp/commit/a3f45babe4eceb8150e7269f7ba79d43ffea38b9
- https://github.com/ingenesis/shopp/commit/bae7af28c773b5b7cf4e37391f04198ed8eb5398

**Comment by sierrab123** [comment]
sierrab123 [5:55 PM] 
Store based in France with 15% VAT rate on Paintings and a 20% VAT rate on everything else

This rate applies EU wide apart from Germany where taxes are 19% VAT on everything

The product has 2 variations with different prices €100 and €200 and is in the category paintings

The addons are Black or Brown Frames at €10 and €20

Shipping is Flat Item Rates at €10



Has 2 categories of products with different tax rates as outline above

Products have addons which also need to be taxed

Merchant sells to countries outside EU

Require the ability to change the variation and country in cart

Just setting this up on my site now

**Comment by sierrab123** [comment]
Store based in France and a 20% VAT rate on everything 

This rate applies EU wide apart from Germany where taxes are 19% VAT on everything

The product has 2 variations with different prices €100 and €200 

Shipping is Flat Item Rates at €10

Products have addons which are also  taxed

The addons are Black or Brown Frames at €10 and €20

Merchant sells to countries outside EU

Require the ability to change the variation and country in cart

So in the EU https://puu.sh/vFAoM/99ad5f7f06.png

Germany https://puu.sh/vFAG8/6b4271986e.png

Outside EU https://puu.sh/vFAyu/dd0615d775.png

**Comment by sierrab123** [comment]
I realised that the variation for the heavier canvas €200 was missing in my tests scenario above

Also for the purpose of the test, as it is not possible to change the addon in the cart, the addon choice (frame colour) is not important and can be dropped

EU  https://puu.sh/vGbDx/bc1f9322cf.png

Germany  https://puu.sh/vGbHz/c28c6038fb.png

Non EU  https://puu.sh/vGbFt/cd2dacf8bb.png

**Comment by shoppdeveloper-com** [comment]
A little more info on why and how tax calculations were altered in 1.3.13
This was the start of things.

**Testscenario:**
base of operation: France
Category              : paintings
Taxrate                 : 10% EUVAT products in category paintings
                              20% EUVAT no conditions
Prices include tax: disabled
Shipping taxed    : disabled
Product1             : Variant1 Euro 100,00
                             Variant2 Euro 200,00
                             Addon1  Euro 10,00
                             Addon2 Euro 20,00
                             Category: paintings
Product2             : Variant1 Euro 100,00
                             Variant2 Euro 200,00
                             Addon1  Euro 10,00
                             Addon2 Euro 20,00
                             Category: none
Shipping            : flat order, everywhere Euro 3,00

Add one of each product to cart with variation 1 selected, no add-ons

Expected in cart (shipping to France)
product1:      unit price Euro 115,00     total price Euro  115,00
product2:      unit price Euro 120,00     total price Euro  120,00
                                                         subtotal:        Euro  235,00
                                                         shipping:       Euro      3,00
                                                         tax:                Euro    35,00
                                                         total:              Euro  238,00

Actual in cart (shipping to France)
product1:      unit price Euro 100,00     total price Euro  100,00
product2:      unit price Euro 100,00     total price Euro  100,00
                                                         subtotal:        Euro  200,00
                                                         shipping:       Euro      3,00
                                                         tax:                Euro     38,00
                                                         total:             Euro    241,00

Taxcalculation is wrong because both taxrates are applied. The code change to `settings()` (in 1.3.14dev) should fix this.

In versions before 1.3.13 (including 1.4) it is not possible to reflect the taxrates in the unit price, in cart, by settingthe taxes option `shopp( 'cartitem.unitprice', 'taxes=on' );`.

**Comment by sierrab123** [comment]
@jonathandavis I am reopening this as it is still not correct By way of example I have 2 sites running 1314 and 1400 (very latest).

Both have the same tax settings see https://puu.sh/w3sKF/712741a323.png

Both have products in the conditional category and outside that category

For the 1314 site see http://1312shopp.azurewebsites.net/shop/aroma/ (conditional category) and http://1312shopp.azurewebsites.net/shop/dylan-test/ (non conditional)

For the 1400 site see http://www.sierrab123.nl/shop/aroma/ (conditional category) and http://www.sierrab123.nl/shop/berlin-nights/ (non conditional)

When you have the similar products in the cart in different tabs you will see that the totals are right but the tax amounts are not.

**Comment by sierrab123** [comment]
See https://github.com/ingenesis/shopp/pull/3804

This does fix the issue but is currently failing tests

**Comment by sierrab123** [comment]
https://github.com/ingenesis/shopp/pull/3804 has been closed, so a new solution is needed
